### ISSUE TITLE
Ejercicios manipulacion de datos

### ISSUE THREAD

**Issue by yabellini** [rse-r/intro-programacion#8]
@paocorrales lo hago como issue para que nos quede aqui.  

Tu propuesta fue:  dar filter y select, luego los ejercicios en grupos, summarise y mutate y ejercicios de nuevo.

Me parecen bien.  Tal vez podemos poner un place holder en el libro con Ejercicios en Grupo para marcarnos que van alli. 

Se que charlamos de subirlos al campus, pero tal vez lo mejor es ponerlo en el libro directamente.  

Podemos pensar en ir liberando algunas de las soluciones posibles pasadas las clases ?  

Los ejercicios que propusiste me parecen muy bien.

**Comment by paocorrales** [comment]
Pensé en ponerlos en el libro pero no me gustaría perder la posibilidad que descarguen el archivo (en vez de copiar y pegar las consignas desde la web). 
Pero podríamos poner una cajita de ejercicio donde esté el link y un "resolver los ejercicios de x y z", funciona también de place holder. 

Si a los resueltos. Tal vez luego de la clase siguiente, tienen una semana para hacerlos y la clase que sigue para consultar antes de ver los resueltos?

**Comment by yabellini** [comment]
Me parece muy bien ambas propuestas.
